apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://helm.traefik.io/traefik
      targetRevision: v26.0.x
      helm:
        valuesObject:
          deployment:
            enabled: true
            kind: DaemonSet
          experimental:
            http3:
              enabled: false
            # kubernetesGateway:
            #  enabled: true
            #  gateway:
            #    enabled: true
          ingressRoute:
            dashboard:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-http-prod
                traefik.ingress.kubernetes.io/router.middlewares: identity-system-ak-outpost-leachnet-proxy-outpost@kubernetescrd
          # metrics:
          #   prometheus:
          #     entryPoint: metrics
          #     serviceMonitor:
          #       jobLabel: traefik
          #     service:
          #       enabled: true
          providers:
            kubernetesCRD:
              enabled: true
              allowCrossNamespace: true
            kubernetesIngress:
              enabled: true
          ports:
            web:
              port: 80
              expose: true
              exposedPort: 80
              nodePort: 80
              redirectTo: 
                port: websecure
            websecure:
              expose: true
              exposedPort: 443
              port: 443
              nodePort: 443
              # http3: false
              tls:
                enabled: true
            traefik:
              expose: true
            mqtts:
              port: 8883
              expose: true
              exposedPort: 8883
              nodePort: 8883
              protocol: TCP
            metrics:
              port: 9100
              expose: false
              exposedPort: 9100
              protocol: TCP
            ldaps:
              port: 636
              expose: true
              exposedPort: 636
              nodePort: 636
              protocol: TCP
          service:
            enabled: true
            spec:
              externalTrafficPolicy: Local
            ipFamilies:
            - IPv6
            - IPv4
            ipFamilyPolicy: PreferDualStack
            type: NodePort
          securityContext:
            capabilities:
              drop: [ALL]
              add: [NET_BIND_SERVICE]
            readOnlyRootFilesystem: true
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
      chart: traefik
    - repoURL: 'https://github.com/duckfullstop/infra-ln/'
      path: k8s/applications/infrastructure/traefik/manifests
      targetRevision: main
  destination:
    namespace: kube-system
    name: leachnet
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
