apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: services
  source:
    repoURL: 'https://github.com/duckfullstop/infra-ln'
    path: k8s/applications/services/media/plex/manifests
    targetRevision: main
  destination:
    namespace: media
    name: leachnet
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
