---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nightscout
  namespace: healthcare
spec:
  encryptedData:
    SECRET_KEY: AgA4z7wQ81zJqjsfL9YQ4OEdf4rsYaNLETHRBplPFCB2sYMcg2IIhXm3mTHdxj8hcdFa6v4MFzD6t3vw29iHXbnJBoy41YWejDwgz7vqg5Sx4T6g/rVGM/IRQ9DxyuHCo1QanQxhY2KdPOH+9pMM8EJ+fERoFNZQekD5lQ+OmR0yjINjvABY/VuZ6w2rUgHWuxdX6ih4m+j/WPsHBXp5zO8yauLDMbgmM6SjUfOVci/OdaiVnAsRbScW4n6Pool4LGzKAcA2f8mUqtqgA7/PLUXOYLqWEqLT7I8NipagGFLUCgfincDOZAwA+Ot+0123Z99nGzut9dCTrnbPQZ28LkNqSTZIh8TxQZEGa2A9zRqnm3f8nMgQBiwFIIiuMIzjAJleaVYcIRyckBD24S+g0aKhrw9CnmLRsFmU+DUIakjiJYhQ6FqhQ43IX2MBAQcZfRFVGITiKKIeN7+pns93OUrqinuka9rV9dDMuv73t1bhCTbFc0jx5n9si1LcEYeMUNpq6gqqAmAwv/dNFAxQlwt+q6WARIjDe87mdQ8ubonMSgFIe8ZSoq+NFVnuoeyBtKiOY90a7dIwFFf4HcG3H7Vj+TCG/leUpPuSkx8CTgZVhBCNlWDik9aIDUX030G172yahdIqV3hUNIkcr6Jfmi6YFUHBD8zSx2qCnih5QGbrEevfBKz37Y2LkQGFnDket4YY5XVsYcWL1isvgkYIboqNS5HE0o7hNyRLPpVRUaP2JA==
  template:
    metadata:
      creationTimestamp: null
      name: nightscout
      namespace: healthcare
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nightscout-mongodb
  namespace: healthcare
spec:
  encryptedData:
    mongodb-passwords: AgATjh3t+se/Bkj3dRBNxYw6Vfkbx5OOyFzB6IRHpGIQ++GJ64avrjO4L42GRxuDdL5FQJpmq+LoG9luoZNjRcO7daWhjTdEsz0H3/ze0d0k/edyHzs/6+Mnuu01tudgScglwFqzf8oy7OmYUY8bU2Eiz6Lr5rhyEcUm6n11kogfazmp4TCITBpgSEZx7xjImQU5yByPR+xMrh9wM6nvO2VJZ9m0Br8Y+tCD1MRwp1AIwK4wPyM8LIubnF+jL0DBJn8OUub0gDbKqb45Y9AxYvvSfmSXT2EN1yeqmfHJvzGz+Xa3sSQ4y5C/PWa9126HIx1zxr2kMg7fxbkNaYDYWK/fTwFOZlOi8Fc0qieHMcwsN3eGx+E3tedWm+Piqvf3hyrgjvoPT6T7WdngovLgZPex/m8Z2KE5YQAH8BVVCmx4ht5LotpPgMijqH6XFPPPSfn+CdhKH3b0ecGZuNObi4y4iU3sll4DoOlSrhdlUHCkDmDBckYT1ni2fbWA6ZtI34b2N7x2ByIkkRmIsQGGee+2o7N4cIpNhlEkamG5J66O8cougjnyKHD2cjJWYmoUOnmuDs40VsrqAmnBsH8L+DvUivmUggYcujs6QQaq3mEzm5ZSlN1wcTpgjuv6t8xcvKbbSvoOqj4YsI5d+bbRKNUCnv0TOAwjZWCoEFXSwDR5ToBpauhrEiqiunjJNJgAVCBVigEt2+d8vGzXotf1cpSwuuerJ495tBowB5h1NjFyLQ==
    mongodb-root-password: AgDGZh8e67LnqPUaKwnrCKUbwjJH6ohU4IKKZw+7gW5sRS7DExyac2x9BmwwcBBJ9wG3ZR+KhcHlslMWWgi7PSWVhkHLnYVg+hXwUGRbTFeq6wQunVxzy20HaohWv7RrdFhhq1FAHtHFC8Rjs5qdik4hH2KT/mkJLjUMNDpMlGlgSJPrJWXCPA/w44Nl4uUGQLBCrGAuHa8z1WPv9CWYesz+alrRBlWtz80B1Zj2vz58jbbLYXaTmkLn6IvOtmjag4EFoReJn0BsKd3UC0UkRaclETwJmYfKg2W7BpXMCj+ObXy+4s8QS4n+PULEwgi01JOmmdPr6pt9bN7wD6zzDdpsuCE4wTA7ffn0WPbIVM5VUmAc/uaqqv26YOx03TrXFRXGsr90S1cIgChSZLMx0qm9VYzBpS2gQYcieNy65dHecoDmKQJ7veghuvNKh+K9bMqvs28P7Iz5IzvblL9RJjS7DS7wXDS3dY5xsqACrJ9/OJxlMdluFrhMUYTpGJ+jEHm0Yv2l7ZvrliGch1slzUdCVnmWTVTGkDhLgDTpDY+lgVluVTCBUEl34EzORIJ1gydN3hlg4wIkD3yfYCnjAMXuhlGY8hFQow51iU5P/3XICAtTUPcNRThDJd9iYeOXJDLLoz26O8Zo+NGrnnevm8eYioO+7pJuXKsMJm0YaB57FtEARbP4sJWSN66UyKEMDZ/7LmUdxdBCnQ2LDCV32+RylyTetaOxu22YT2d9ayCjeQ==
  template:
    metadata:
      creationTimestamp: null
      name: nightscout-mongodb
      namespace: healthcare
    type: Opaque
