apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: thebiggame
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Elements providing resources for theBIGGAME lan parties.
  destinations:
  - name: leachnet
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceNamespaces:
  - 'thebiggame'
  sourceRepos:
  - '*'