advanced:
  last_seen: ISO_8601
  log_level: info
  log_namespaced_levels:
    z2m:mqtt: warning
  log_output:
    - console
  network_key: '!secret NETWORK_KEY'
  report: true
  rtscts: false
external_converters:
  - HIVELDSSIREN001.js
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
devices: 
  - devices.yaml
frontend:
  port: 8080
groups: 
  - groups.yaml
homeassistant:
  legacy_entity_attributes: false
  legacy_triggers: false
mqtt:
  base_topic: zigbee2mqtt
  user: '!secret MQTT_USER'
  password: '!secret MQTT_PASS'
  server: 'mqtt://mosquitto.database.svc.cluster.local:1883'
permit_join: false
serial:
  port: /dev/ttyUSB0