apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: antennas
  namespace: iptv
spec:
  encryptedData:
    tvhUrl: AgAkVORo/Go2UM5KHjFR3pu9lHuQMxiOIUxxt59yjyiWJYFg8HxYhYJG/kzq6S9Uqy7nWHSUJiZXYd0JKfH2uhQ2ttcP/pNx8BH7LNJTio7Ke5MeCvj4TQkbi2oCAhvNd6vNt0Ai/Vetf6AdepAnFwF1GvnxnzZxUjGQNJjP05GmfhIMStd5kAzX30VMfortgOu+K5i9DEZYQgNOtGi3JrtDm8e8lzSVuslcfb7y/IlIxUmMgbInKfnGHf8FcCygfnOGNgXHRR2XNUSaFB0D8UkJhYrDHwQGjlFkNNsiyc/YkWfr4MxCK3Vu66syigEnwVHzHw6gSx9MxhgypoUTptLN/zaBL/S7LSShzLoPvf1mLsCtFuats3ORxbATiYd240OfOFUTJzH4ULbJdU3PC2ExqyQPpb8UlOjV2sTw1WXoTt7vkIau0wLKb0p4czWM9n3q+2g2zhcMNeSG+eXjZFKe/ndHfkK1Uz8ydtXZVZrE445c3ygqgMsL5xVBQ3CjhA4C0ytNCn/HvKFygWZ+JoNSXZKSykCkg90dgRmJQVKOlXXeAxTIV4phvpN6dN6t9OVyPhMWy8RPAu4+vIWZXOvh4mGe+/yyayGVP7t5eIwLPyXKJkzAE4Zrko66O9QEHxl1qOIXzOH9lNmk1ja3yGmHDEvAviRv+JDxNzWo1W3DDd9GK8+EtVTmwB5H+T0k8zwqboRLiEeExwPttaC7139iXK2LRmrpuZ9Txlt1q1A4I1TLzdPILgKjjLOvdZMWU8C8a58kHgikMREZ
  template:
    metadata:
      creationTimestamp: null
      name: antennas
      namespace: iptv
    type: Opaque
---
