apiVersion: v1
kind: Service
metadata:
  name: tvheadend
spec:
  ports:
  - name: http
    port: 9981
    targetPort: http
  - name: rtsp
    port: 9982
    targetPort: rtsp
  - name: plex
    port: 5004
    targetPort: hdhr
  selector:
    app: tvheadend