apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tvheadend
spec:
  selector:
    matchLabels:
      app: tvheadend
  replicas: 1
  serviceName: "tvheadend"
  template:
    metadata:
      labels:
        app: tvheadend
    spec:
      containers:
        - name: tvheadend
          image: ghcr.io/linuxserver/tvheadend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 9981
            protocol: TCP
            name: http
          - containerPort: 9982
            protocol: TCP
            name: rtsp
          resources:
            requests:
              duck.moe/tuner-dvb-s: "2"
              duck.moe/tuner-dvb-t: "2"
            limits:
              duck.moe/tuner-dvb-s: "2"
              duck.moe/tuner-dvb-t: "2"
          #resources:
          #  requests:
          #    memory: "250Mi"
          #    cpu: "500m"
          #  limits:
          #    memory: "2Gi"
          #    cpu: "2"
          securityContext:
            privileged: true
            procMount: Default
          env:
          - name: TZ
            value: "Europe/London"
          - name: PUID
            value: "911"
          - name: PGID
            value: "65536"
          volumeMounts:
          - name: config
            mountPath: /config
          - name: timeshift
            mountPath: /timeshift
          - name: recordings
            mountPath: /recordings
          - name: dev-dvb
            mountPath: /dev/dvb
          - name: dev-dri
            mountPath: /dev/dri
          # livenessProbe:
          #   httpGet:
          #    path: /
          #    port: 8080
          #  initialDelaySeconds: 20
          #  periodSeconds: 5
        - name: antennas
          image: ghcr.io/jfarseneau/antennas:4.2.0
          resources:
            requests:
              memory: "75Mi"
              cpu: "5m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - name: hdhr
              containerPort: 5004
          env:
            - name: ANTENNAS_URL
              value: "http://tvheadend.ln-media.svc.cluster.local:5004"
            - name: TVHEADEND_URL
              valueFrom:
                secretKeyRef:
                  name: antennas
                  key: tvhUrl
                  optional: false
            - name: TUNER_COUNT
              value: "4"
          startupProbe:
            httpGet:
              path: /discover.json
              port: http
            failureThreshold: 12
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /discover.json
              port: http
            timeoutSeconds: 60
          livenessProbe:
            httpGet:
              path: /discover.json
              port: http
            timeoutSeconds: 60
      volumes:
      - name: dev-dvb
        hostPath:
          path: /dev/dvb
          type: Directory
      - name: dev-dri
        hostPath:
          path: /dev/dri
          type: Directory
      - name: timeshift
        emptyDir: {}
      # temporary directory for recordings, will eventually be pointed at storage
      - name: recordings
        emptyDir: {}
        
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: "vault-fast-nfs"
      resources:
        requests:
          storage: 500Mi