apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr24feed
  namespace: flight-tracking
spec:
  selector:
    matchLabels:
      app: fr24feed
  replicas: 1
  template:
    metadata:
      labels:
        app: fr24feed
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  # Runs in qemu if not on arm64
                  - arm64
      containers:
        - name: fr24feed
          image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest
          # command: ["config/", "dashboard"]
          tty: true
          ports:
          - containerPort: 8754
            protocol: TCP
            name: http
          resources:
            requests:
              memory: "20Mi"
              cpu: "500m"
            limits:
              memory: "50Mi"
              cpu: "1"
          env:
          - name: BEASTHOST
            value: "ultrafeeder"
          - name: BEASTPORT
            value: "30005"
          - name: FR24KEY
            valueFrom:
              secretKeyRef:
                name: ads-b
                key: FR24_SHARING_KEY
          - name: BIND_ADDRESS
            value: "::"
          livenessProbe:
            exec:
              command:
                - /scripts/healthcheck.sh
            periodSeconds: 60
            failureThreshold: 3
            timeoutSeconds: 30
          startupProbe:
            exec:
              command:
                - /scripts/healthcheck.sh
            initialDelaySeconds: 240
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 30
