apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infra-monitoring
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/charts/crds
    targetRevision: kube-prometheus-stack-55.8.3
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
      - Replace=true
  destination:
    namespace: monitoring
    name: leachnet