---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 6h
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/duckfullstop/infra-ln
  ignore: |
    # exclude all
    /*
    # except the k8s manifests
    !/kubernetes
    # although there are a few other things we don't need
    /kubernetes/**/*.txt
    /kubernetes/**/*.md
