---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 6h
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/duckfullstop/infra-ln
  ignore: |
    # there are a few other things we don't need
    /**/*.txt
    /**/*.md
