apiVersion: v1
kind: Service
metadata:
  name: wyoming-piper
  labels:
    app: wyoming-piper
spec:
  ports:
  - name: wyoming
    port: 10200
    targetPort: wyoming
  selector:
    app: wyoming-piper
  # Pending https://github.com/rhasspy/wyoming/pull/7/
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack