apiVersion: v1
kind: Service
metadata:
  name: wyoming-whisper
  labels:
    app: wyoming-whisper
spec:
  ports:
  - name: wyoming
    port: 10300
    targetPort: wyoming
  selector:
    app: wyoming-whisper
  # Pending https://github.com/rhasspy/wyoming/pull/7/
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack