apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
spec:
  selector:
    matchLabels:
      app: wyoming-whisper
  replicas: 0
  template:
    metadata:
      labels:
        app: wyoming-whisper
    spec:
      containers:
        - name: whisper
          image: rhasspy/wyoming-whisper
          args:
            - --model
            - tiny-int8
            - --language
            - en
          ports:
            - containerPort: 10300
              protocol: TCP
              name: wyoming
          