# This special Application object synchronises all Applications.
# https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/#app-of-apps-pattern
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: leachnet
  project: infrastructure
  source:
    repoURL: 'https://github.com/duckfullstop/infra-ln/'
    path: k8s/applications/infrastructure
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: leachnet
  project: services
  source:
    repoURL: 'https://github.com/duckfullstop/infra-ln/'
    path: k8s/applications/services
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-monitoring
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: leachnet
  project: services
  source:
    repoURL: 'https://github.com/duckfullstop/infra-ln/'
    path: k8s/applications/infra-monitoring
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true