apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-test
  namespace: default
  labels:
    app: grafana
spec:
  storageClassName: vault-fast-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi