apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: ultrafeeder
  name: ultrafeeder
spec:
  endpoints:
  - interval: 60s
    port: metrics-1
    path: "/metrics"
  namespaceSelector:
    matchNames:
    - flight-tracking
  selector:
    matchLabels:
      app: ultrafeeder
