apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: services
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      chart: mariadb
      targetRevision: "15.0.*"
      helm:
        valuesObject:
          architecture: "standalone"
          auth:
            existingSecret: mariadb
            usePasswordFiles: true
          fullnameOverride: "mariadb"
          # TODO move to longhorn
          # primary.persistence.existingClaim: mariadb-data
          primary:
            persistence:
              storageClass: "vault-fast-nfs"
              size: "10Gi"
          secondary:
            replicaCount: 0
            # secondary.persistence.storageClass: "longhorn-fast"
            # secondary.persistence.size: "10Gi"
          volumePermissions:
            enabled: true
          metrics:
            enabled: false
            serviceMonitor:
              enabled: false
    - repoURL: 'https://github.com/duckfullstop/infra-ln'
      path: k8s/applications/services/database/mariadb/manifests
      targetRevision: main
  destination:
    namespace: database
    name: leachnet
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
