apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
spec:
  selector:
    matchLabels:
      app: wyoming-piper
  replicas: 1
  template:
    metadata:
      labels:
        app: wyoming-piper
    spec:
      containers:
        - name: piper
          image: rhasspy/wyoming-piper
          args:
            - --voice
            - en-gb-southern_english_female-low
          ports:
            - containerPort: 10200
              protocol: TCP
              name: wyoming
          
