apiVersion: apps/v1
kind: Deployment
metadata:
  name: vigor-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: vigor
  replicas: 1
  template:
    metadata:
      labels:
        app: vigor
    spec:
      containers:
        - name: exporter
          image: docker.io/duckfullstop/vigor-exporter
          args:
            - -host
            - "10.0.254.1"
            - -username
            - admin
            - -password
            - admin
          ports:
          - containerPort: 9103
            protocol: TCP
            name: metrics
          resources:
            requests:
              memory: "10Mi"
              cpu: "50m"
            limits:
              memory: "25Mi"
              cpu: "100m"
