apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: ln-data
spec:
  interval: 5m0s
  chart: 
    spec:
      chart: vaultwarden
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: vaultwarden
      valuesKey: mail-host
      targetPath: smtp.host
      optional: true
    - kind: Secret
      name: vaultwarden
      valuesKey: mail-port
      targetPath: smtp.port
      optional: true
    - kind: Secret
      name: vaultwarden
      valuesKey: mail-security
      targetPath: smtp.security
      optional: true
    - kind: Secret
      name: vaultwarden
      valuesKey: mail-auth-mechanism
      targetPath: smtp.authMechanism
      optional: true
  values:
    domain: https://bitwarden.theleachfamily.me.uk
    invitationOrgName: "leachnet."
    signupsAllowed: false
    signupsVerify: true
    adminToken:
      existingSecret: "vaultwarden"
      existingSecretKey: "admin-token"
    smtp:
      existingSecret: "vaultwarden"
      from: "bitwarden@theleachfamily.me.uk"
      username:
        existingSecretKey: "mail-user"
      password:
        existingSecretKey: "mail-password"
    ingress:
      enabled: true
      class: "traefik"
      hostname: bitwarden.theleachfamily.me.uk
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http-prod
      pathType: ImplementationSpecific
      tls: true
      tlsSecret: "vaultwarden-cert"
    data:
      name: "vaultwarden"
      size: 1Gi
      class: "manual"
      keepPvc: false
