apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
  namespace: homeautomation
spec:
  selector:
    matchLabels:
      app: esphome
  replicas: 0
  template:
    metadata:
      labels:
        app: esphome
    spec:
      containers:
        - name: esphome
          image: esphome/esphome:latest
          args:
            - dashboard
            - '--address=::'
            - /config
          ports:
          - containerPort: 6052
            protocol: TCP
            name: http
          - containerPort: 6123
            protocol: TCP
            name: comms
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "4Gi"
              cpu: "4"
          env:
          - name: ESPHOME_DASHBOARD_USE_PING
            value: "true"
          volumeMounts:
          - name: config
            mountPath: /config
          - name: cache
            mountPath: /cache
          - name: build
            mountPath: /build
          - name: secrets
            mountPath: /config/secrets.yaml
            readOnly: true
            subPath: secrets.yaml
          livenessProbe:
            httpGet:
              path: /ping
              port: 6052
            initialDelaySeconds: 20
            periodSeconds: 5
      volumes:
      - name: secrets
        secret:
          secretName: homeassistant
      - name: config
        persistentVolumeClaim:
          claimName: esphome
      - name: build
        persistentVolumeClaim:
          claimName: esphome-build
      - name: cache
        emptyDir:
            # medium: "Memory"
            sizeLimit: 8G
