apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome
  namespace: homeautomation
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "vault-fast-nfs"