apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-monitoring
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Infrastructure elements related to monitoring of the cluster, its workloads, and the network.
  destinations:
  - name: leachnet
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'