apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: database
spec:
  encryptedData:
    postgres-password: AgBWA+CYlFMlRy39zj17sKf5dED50LVQhhfClrzVJfJB5zmeYBeuxPLKixYvEuThxKhozsmvniu2tzo8YtEHSXOoUG09cZKWijhxRexLI0GciCc6aRv1ctG+SjNrOLyniU1n6v+72m6hWRgS+Affw9jbbJ1Q+uOMzYVwQc8Acrr8wV+DYv3bXevtAL1ttJmKcyziES7gJQ0zX/4EBG47XRSQDbC0tr8JiTfcilbKmXW9I1Tu5B5myPPucLXYla3YzYrpAn3xmt7WTKApU3I1A/dGao7U6TtdKf5MqTcVZhPu9FAQJpepVLbiwWPovUvg4ldP4m4IQBSu7QdKbFfLBLL7WdUwiJc3Vq6R7jbYvV9MobeaL1rDD+eExWHLbJm37PEGVBYf2jJBHhn7XZc9fzOzgOWQgrdMyTUwX/yS66Ur40sw+KdGPON1qhrFgIY6a98iynfGCWCR5SoN37QOocueqT8556APsrqA83CK7XxeGJdVyFZCtSjHZ6sbR8V4R03w+1PKYSw3orWdtpJLm5XIk6d2d9vBHFjuBC2KlI8wXgd8TzdtRsWp9Ovw5u39Cy+kxunfxNZ97mImuWVSiNjX1v1rth/gyDNJQKZjXRfHyqWMNXSKi6uvZrCgvtafRwvsLOWJhL6oiqQ0Rfp8tAOSb3h1LvtiGHFbQ5UF75K1w6WFfOOhPVe9U7SuiHpkhL0iEQz5c6NpJDpqbuxRk1qrY8FJSlE+geo4MKgG3Lv3GQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: database
    type: Opaque
---
