apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: database
spec:
  encryptedData:
    postgres-password: AgBd5tX7Gzn945f0LDjLi6ZIKrArf7brX1GQk/JZ3VhmQMysfgXmXoZLrzGwsBGHi2Y5H13IzfFo/l4HOzSqHU44qzuqEoEKDNRtT3CVSrYHaY2jK8qaI6asid4wGj/rx7mkFJzyV5dOLM+OYJ/PcMJG4ARI37BFzbgF4G0lEOwzEgxgXxWGcEwrnR/GmWA4gLKgDoYloN5nyaST2gSoakhuCOJFlfA/+YFD37TkoF6iSpDF9kNYpI7gE1jHCIe06rFVDwqO2m5FklIKY+1piR5+cCfpwBmTXnTDU5Q2DbBSNbnWggwzJ/AP1YI4ke6cUuQHb8ECNf6MNN0rN2aJPdNtcRSSaEuumBmZO/T9Q9yOXB2GgToCNdvEoSysha1UfXnthRZ2UBwsD5V6jnOqUVe/m4HuKaIF+2sUmQDieol6CBwMnNEDQ5in0sT4trQ034lJPqej791am8ivMi9MhcDksTSMnh2ZgizzdCBN495dE8J4zgJc/g6a7R32mwQnXyhhi/uiqNDEmXVcBIXihYv+jSLDz7msRoU+sk3CDuOLKceEIgxn0qa6Ek0jzK7Q1XU6MJGwFfVPEKX0JBdzh015ohyPKOKZIMd6MBKrQS4TiFQiYskpurQx0+RFJoduUie0/64InLJIL9rGFex21G4aZGNzJh+o6KB9l4lEsdOjMsKp9XcgiOBvuEle5GnpHhLnvyXk/WOYsf3SKlKKLyEXvbOWdRbnpJXeYfQeuLGN2g==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: database
    type: Opaque
---
