apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: services
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      chart: postgresql
      targetRevision: "13.2.*"
      helm:
        valuesObject:
          image:
            tag: 14
          auth:
            database: "postgresql"
            existingSecret: "postgres"
          primary:
            persistence:
              enabled: true
              storageClass: "vault-fast-nfs"
              size: "50G"
          metrics:
            enabled: false
            serviceMonitor:
              enabled: false
          postgresqlDatabase: "default"
          fullnameOverride: "postgresql"
    - repoURL: 'https://github.com/duckfullstop/infra-ln/'
      path: k8s/applications/services/database/mariadb/manifests
      targetRevision: main
  destination:
    namespace: database
    name: leachnet
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
