apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rtl433
  namespace: homeautomation
spec:
  encryptedData:
    secret.conf: AgBTwzUuS7XZkKKC2NXhd+yyiT2XJoQUchkKhOAmOEvNTD5XjAhXk1FuiZIu52PJrB5pNiYMMOxPzzs7bIyEgvJEMXqA6cest2u64+3b1B4DdIdJKqaHt5Z62LBMJpmQi1a767TNsrAasgWBlZuAMsDa9LQQaL9oRWeZyUM93/ZO1XUaztGL+Nil7mcmM77BMQR72A8Kk57Z5EESTnqQC9Ps2DgUp1XILKEqKN8jlel/DqDJG66SpCCPQ8PGzxFmngIxFvaeyph7A/JcFqx2s2RAejh8m5dtWZNG0ximKZyRXP/BhaFJFy5rKbriG9UbtK7ut2cBCcMVa/YEgoxR5M+pWBI7fKAm+9dESGkcNc7zAfSAz2PcqqdVjq/fwwxNukAAobdXk7FHV9FGjg5D4czqlZeyHPyKEpaZ5OlaN5iZtb+sv2XDw4+tu81/STaUxEbhZB4BVPJbSIGjd/ki8Q0iFomcYENeb3uzX/LvlxevcmRPI8X7Cq5/+FU0P+JQftNG9mzVJs65v8CB+HcDETo5veueExW109DfDKIwed5GcP1KLdEsqnYMLbrhd/h7PImaLF05P9+s3pauqvMyrjRgUIeTi3A0OPPH6huwnrh+Rf3GgUhmVNn5LvXn8Qx5m+AQUsCRix5O34hBgDM/JxQu3Y7hItOnnBHozDtHh6EKbBbryv7DyxTaElrAyYASSQ7uE7FXnh5MD1GYsh9QzZwxE+6ocOxp7mtENm832m70LTOPvOtFo3wSxqRO+/mCNM9Qmz/D9l8jk02xb1KDFUsSM9AMfflDl6KycnNz+KX719aRm3lM6rAB9wSZ4qIiGhe3afklaVQ2NZhLnvGRdgogjUSzTMCczVPYN/hSIykWLvYOqerE/c0ir4Zc05orS7lQsaZcMzcJxuxTGnzvj43s5RZrM9f2/C94u7UoLXpObugSI5EAVVm2kZZVl2xK087DB8X68vykWqKQ9ITlBekVi7ncPdJ1ULG5/CcNd/IEIs+0fzObmiascgn+zGHs7iLu606BwuGQOTPGjw4nxJ4a/+MdDGmjCeb+dt/kwGo49fTTdHzj9Sf+PUwsrz2c4VtMVBcNsgQPc1cU9KgP/MdsAmsyvxSEoWHORQXStQBJLOkxSrk=
  template:
    metadata:
      creationTimestamp: null
      name: rtl433
      namespace: homeautomation
    type: Opaque
---
