apiVersion: v1
kind: Service
metadata:
  name: flightaware
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: mlat
    port: 30105
    targetPort: mlat
  selector:
    app: flightaware