apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- compact.yaml
- compact-servicemonitor.yaml
- compact-svc.yaml
- query.yaml
- query-servicemonitor.yaml
- query-svc.yaml
- secret.yaml
- store.yaml
- store-servicemonitor.yaml
- store-svc.yaml