apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-thanos-query
  namespace: monitoring
spec:
  jobLabel: thanos
  selector:
    matchLabels:
      app: thanos-query
  namespaceSelector:
    matchNames:
      - 'monitoring'
  endpoints:
    - port: http-query
      path: /metrics
      interval: 5s