apiVersion: apps/v1
kind: Deployment
metadata:
  name: readsb
  namespace: ln-ads
spec:
  selector:
    matchLabels:
      app: readsb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: readsb
    spec:
      containers:
        - name: readsb
          image: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf:latest
          tty: true
          ports:
          - containerPort: 8080
            protocol: TCP
            name: http
          - containerPort: 9273
            protocol: TCP
            name: metrics
          - containerPort: 30005
            protocol: TCP
            name: beast
          - containerPort: 30105
            protocol: TCP
            name: beast-reduce
          resources:
            requests:
              memory: "50Mi"
              cpu: "250m"
              dev.duck.moe/radio-ads: "1"
            limits:
              memory: "100Mi"
              cpu: "500m"
              dev.duck.moe/radio-ads: "1"
          securityContext:
            privileged: true
            procMount: Default
          env:
          - name: DISABLE_WEBAPP
            value: "false"
          - name: DISABLE_PERFORMANCE_GRAPHS
            value: "true"
          - name: ENABLE_PROMETHEUS # Listens on :9273/metrics by default
            value: "true"
          - name: TZ
            value: "Europe/London"
          - name: READSB_DCFILTER
            value: "true"
          - name: READSB_DEVICE_TYPE
            value: "rtlsdr"
          - name: READSB_FIX
            value: "true"
          - name: READSB_GAIN
            value: "autogain"
          - name: READSB_LAT
            valueFrom:
              secretKeyRef:
                name: ads-b
                key: SITE_LATITUDE
          - name: READSB_LON
            valueFrom:
              secretKeyRef:
                name: ads-b
                key: SITE_LONGITUDE
          - name: READSB_MODEAC
            value: "true"
          - name: READSB_RTLSDR_DEVICE
            value: "00001000"
          - name: READSB_RTLSDR_PPM
            value: "1"
          - name: READSB_RX_LOCATION_ACCURACY
            value: "2"
          - name: READSB_STATS_RANGE
            value: "true"
          - name: READSB_NET_ENABLE
            value: "true"
          - name: READSB_NET_REDUCE_OUT_PORT
            value: "30105"
          volumeMounts:
          - name: usb-ads-b
            mountPath: /dev/bus/usb
          - name: readsb-autogain
            mountPath: /run/autogain
          - name: run
            mountPath: /run/readsb
          - name: varlog
            mountPath: /var/log
          livenessProbe:
            exec:
              command:
                - /scripts/healthcheck.sh
            periodSeconds: 60
            failureThreshold: 3
            timeoutSeconds: 30
          startupProbe:
            exec:
              command:
                - /scripts/healthcheck.sh
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 30
      volumes:
      - name: usb-ads-b
        hostPath:
          path: /dev/bus/usb
          type: Directory
      - name: readsb-autogain
        persistentVolumeClaim:
          claimName: readsb-autogain
      - name: run
        emptyDir:
          medium: "Memory"
          sizeLimit: 64M
      - name: varlog
        emptyDir: {}