apiVersion: v1
kind: Service
metadata:
  name: readsb
  labels:
    app: readsb
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: metrics
    port: 9273
    targetPort: metrics
  - name: beast
    port: 30005
    targetPort: beast
  selector:
    app: readsb
