apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flood-config
  namespace: download
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  storageClassName: "vault-fast-nfs"