apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readsb-autogain
  namespace: flight-tracking
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: vault-fast-nfs