apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: homeassistant
  namespace: flux-system
spec:
  image: ghcr.io/home-assistant/home-assistant
  interval: 6h
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: homeassistant
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: homeassistant
  policy:
    semver:
      range: '>=2023.1'
