apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vigor-exporter
  namespace: argocd
spec:
  project: infra-monitoring
  source:
    repoURL: 'https://github.com/duckfullstop/infra-ln/'
    path: k8s/applications/infra-monitoring/vigor-exporter/manifests
  targetRevision: main
  destination:
    namespace: monitoring
    name: leachnet
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
