apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: vigor
  name: vigor-exporter
spec:
  endpoints:
  - interval: 60s
    port: metrics
    path: "/metrics"
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: vigor
