apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-slow
  namespace: kube-system
spec:
  interval: 1m0s
  chart: 
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    mode: standalone
    drivesPerNode: 1
    replicas: 3
    pools: 1
    resources:
      requests:
        memory: 2Gi
    persistence:
      enabled: true
      existingClaim: minio-data-slow
    metrics:
      serviceMonitor:
        enabled: true
    ingress:
      enabled: true
      hosts:
        - minio.net.theleachfamily.me.uk
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http-prod
      tls:
        - hosts:
          - minio.net.theleachfamily.me.uk
          secretName: minio-cert
    consoleIngress:
      enabled: true
      hosts:
        - console.minio.net.theleachfamily.me.uk
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http-prod
      tls:
        - hosts:
          - console.minio.net.theleachfamily.me.uk
          secretName: minio-console-cert