apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data-slow
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/vault/services/minio"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nagoya
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-slow
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: manual