apiVersion: apps/v1
kind: Deployment
metadata:
  name: weconnect-mqtt
  namespace: ln-home
spec:
  selector:
    matchLabels:
      app: weconnect-mqtt
  replicas: 1
  template:
    metadata:
      labels:
        app: weconnect-mqtt
    spec:
      initContainers:
        - name: init-wait-for-mqtt
          image: busybox
          command: ['sh', '-c', 'until nc -zv mosquitto.ln-database.svc 1883; do echo waiting for mosquitto; sleep 2; done;']
      containers:
        - name: weconnect-mqtt
          image: ghcr.io/tillsteinbach/weconnect-mqtt:0.45.1
          env:
            - name: TZ
              value: "Europe/London"
            - name: LC_ALL
              value: "en_GB"
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: weconnect
                  key: user
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weconnect
                  key: password
            - name: BROKER_ADDRESS
              value: "mosquitto.ln-database.svc"
            # This is really silly.
            - name: ADDITIONAL_PARAMETERS
              valueFrom:
                secretKeyRef:
                  name: weconnect
                  key: additional_parameters
          # resources:
          #  requests:
          #    memory: "50Mi"
          #    cpu: "10m"
          #  limits:
          #    memory: "1Gi"
          #    cpu: "2"