apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-downloads-duck-torrents
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: "vault.leachnet"
    path: "/mnt/vault/downloads/duck/torrents"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-downloads-duck-torrents-complete
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: "vault.leachnet"
    path: "/mnt/vault/downloads/duck/torrents/complete"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-downloads-duck-torrents-complete-deduplicate
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: "vault.leachnet"
    path: "/mnt/vault/downloads/duck/torrents/complete/deduplicate"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-downloads-duck-torrents-downloading
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: "vault.leachnet"
    path: "/mnt/vault/downloads/duck/torrents/downloading"
