apiVersion: apps/v1
kind: Deployment
metadata:
  name: owntracks-recorder
  labels:
    app: owntracks-recorder
spec:
  selector:
    matchLabels:
      app: owntracks-recorder
  template:
    metadata:
      labels:
        app: owntracks-recorder
    spec:
      containers:
      - image: owntracks/recorder:latest
        name: recorder
        resources:
          requests:
            memory: "100Mi"
            cpu: "150m"
          limits:
            memory: "200Mi"
            cpu: "300m"
        env:
        - name: OTR_STORAGEDIR
          value: "/store"
        #- name: OTR_CAFILE
        #  value: "/etc/ssl/certs/ca-cert-DST_Root_CA_X3.pem"
        - name: OTR_HOST
          value: "mosquitto.database.svc.cluster.local"
        - name: OTR_HTTPHOST
          value: "[::]"
        - name: OTR_HTTPPREFIX
          value: "https://recorder.owntracks.theleachfamily.me.uk"
        - name: OTR_PORT
          value: "1883"
        - name: OTR_USER
          valueFrom:
            secretKeyRef:
              name: owntracks
              key: mqtt-user
        - name: OTR_PASS
          valueFrom:
            secretKeyRef:
              name: owntracks
              key: mqtt-password
        - name: OTR_PRECISION
          value: "7"
        - name: OTR_GEOKEY
          valueFrom:
            secretKeyRef:
              name: owntracks
              key: geokey
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          timeoutSeconds: 1
          failureThreshold: 30
        ports:
        - containerPort: 8083
          name: http
        volumeMounts:
        - name: data
          mountPath: /store
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: owntracks
