apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment-frontend.yaml
- deployment-recorder.yaml
- ingress.yaml
- pvc.yaml
- secret.yaml
- service-frontend.yaml
- service-recorder.yaml

configMapGenerator:
- name: owntracks-frontend-config
  namespace: owntracks
  files:
  - config.js