apiVersion: v1
kind: Service
metadata:
  name: thanos-store
  namespace: monitoring
spec:
  ports:
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: grpc
  selector:
    app: thanos-store
  type: ClusterIP