---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dawarich
  namespace: locationhistory
spec:
  encryptedData:
    redis-password: AgAtfGynNIHToIN+AZn9dFX6TTqS+xcxmQSKzDoefTAlaQSPNP2SP0iz87WnaTG/EMeYyNdypioP2lxH4AV9U2ZhmFyKuKLG+Xybtij9MbqUwxiceLH1uLsL08VF0d4oe+4LnpGRDVfkJMaE5pHdK/sIgIHlmzl5B4iL85a3R8Em6Qo7Ne68FyEEeBDYXrNxW8PcCs0npy0/SKwK5uT+F0e8U9Rh80zuZFHJo5yvhm4amI0yITbORkvio94Ml1gqufY3wda8cvgQMk+k0ITou+rHroE1D5m/u6Z7rHuTRDqAtjvGD+sEce54hPvd/nRojBc1o+D7RmLuq+d9eY6kXt0onMVv7nSA6xevwyBENCmoZiHYTHvjnQMelzksBKt0kICwb+d9dKe2xA2vk4wi3lzp0XRQG+aquocuBA8QiIXtGsSy69DtWoxpmLaswZ4LTcX6doRWTfQKWNMapZBXtdgIgjpobrlI+P3hyGjaGE2g2st/yNDmbQRFFynpqPkbSQWN2lvRO9N+7OPoaL/tftj9TZs19maqnOhu9OS1CkeF6ELCpL4ULtEdih7L70R4p1N8sXE38QnI88r3m08vh163KTqHS5m6zvA3fBDbheUbvLT9GJfOs8A5kXAE4J8IDKu6CXjcbh+e4gxh+6rCbkguNB5unINtzTLh0zcUGTJEHLNZx3AGu9FDdM2aHKxA/TlGv8MrOQREK22tZHozBxdh
  template:
    metadata:
      creationTimestamp: null
      name: dawarich
      namespace: locationhistory
    type: Opaque
