---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dawarich
  namespace: homeautomation
spec:
  encryptedData:
    redis-password: AgCilG7WfK5CVMwjwclg1Kb6uoPOfkTY8Ik67cawiT1eMRjidETly44alP+IUt8djOYaoyVFYjPiKLDCSgdT+Ry6AIece74twufDcWOF/g0KUMJSixuiandYKkKlrlP+fj9nFezTwX+AgkFxu45nS5DaLhlp/+ReD4Jz2AgKV+KSaB0eJeKjTm+gM/TXAq4WIaAERWxqQe/jLqmqBTT2AV5m69n6uopm6K9hmZBkcm7pLu0261qgG8ChSnLt9QfJIESCU4BV7iI7JNdMPuKIaADCEzFyRfrivOweA8GI8/tekvhG/LgA6yykshl4Ls6P9UPmLy48+CEcrPpzNi0U31mwsule2AsMjGZssEQGn+s+zGYMzHlmRKXC6sAmg+PBZitukQxmkse79uXHd4AfEHMm+nOp6MZpw14Ok72k35KlGg4bzOiJYcKkncSuEQE5XyRS47DSFZPhFLkSVUR74+fcg4fmNPsbLtPZQaJvMbQ5iB9g8gmDqCQgQySjoqRKxryyerFarkwsXS/RyDan4zwNWsoncVLXy22YanEMlLAeSMYwORm0UGQ00F88cRc6eVk6LIg6mcKhnmZbyImzKI4Hqvwp5a9NePPpOO2iFFSSIkTmWnMRrByuLpUWkQ+leuLTMH2EAZVt/RJXXE0CnDAO17a7HRy1K01f4y/swuHvyGAPt/75s61LzY+VlII/urtsMLYwTWPAn0BHFxIvJGKR
  template:
    metadata:
      creationTimestamp: null
      name: dawarich
      namespace: homeautomation
    type: Opaque
