apiVersion: v1
kind: Service
metadata:
  name: adsbexchange
spec:
  ports:
  - name: http
    port: 31090
    targetPort: http
  - name: mlat
    port: 30105
    targetPort: mlat
  selector:
    app: adsbexchange
