apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flood
  namespace: dn-downloads
spec:
  encryptedData:
    qb_password: AgAnIB3/9UaryjyD6sc2SbMdrDCn/1vXaFOyV8BLaIKGsh1okwL5xkCnR/1kMUMN/qOTRSfgBfdsABx33NX515PgGoT75DrZcwqLK2iaCKx+rlsQUt+sD4shilWuUaYdcfBSW1gqm1dDsEDk/3ipmZCOx2004sfQgY00oWT2dNl5Pe5WzaBRHAXvFxJww3/ksmkBrCb26k5xuBBh7T0dGXtYtLzcG46/tZfwDCRXNTnftK9WEdVrXB9AFzgV6HToObMncRySO1CU5OVnY9iARGjKkOUXBhsMeZtsSoaz/j1wNe7kDbs1IJ7h9uKAyER7TJeBBSyQ3MfQglQTgbtDLO9Pr2guOvl2C59dhyMmp9EP81QsMlcE44eyT16tlq7M4uh8C6fpFcSYoNrmUfuLeJ7nPo/dAWgLG5jKxxCp44KKyKlQ8HrUGIW/Cw3Z/Id/K4wGvTMlwMvKG93V2CQviyjCc9CO0U7Qw/9gNVF41njrdjDXU3dRy8HZecV75VRcDX6vgFkhjv4WMOnyeWdCiqbdStKqvTzNjApxvjirw5UvxPtj4lhEpjNthIwneodUhy2gMtq3Kzpld4h0ncAbXQ+ElLW0DN5L59VyV9YiuQzShK3VagflUZhOykHrpOaXbwBz5s8EsGbfb639WSC2CJ6j2FHDhKwmcSUBnmRV7xZeNJxMNR5k7LzOxGKLuBsTHXrSq++i/oQQBTQ1
    qb_username: AgA05ytg9odV+j566IF0hqxufBEWZacnlMIa404WNlJSf/+cddgQdDa//m9o5VKKtfYTVpbhP4+GhfC4Sggt8MT2Lcsnp8DGl2iuI2x+9mbxvCdgGjoCXVL+bpvrmDzUiFbsOG1aJyXeotL0r0gaXPCbzpXw3N19qj+nzst0OiCMVeAhF/HipGROHnXfYoAPlZrx9kHEmGBCVaZGt4QZFr/k0IeCZ3qaNnmCakftgmgI69UI82pzMPq/8FKVeQxveOwj65QgT9MksmJn5awzh2cIEdTnUUVXUmB98Pw4Xv7V5+fh8vhzvN9ACsKNkbkDFdTlEpzHZolHVev8MPhuZz8MTVQqQZfrFEo2k8MwuwKmlNUxDcYLnrIV2f8I9Ds/UEjOfLW8LgWJM7U8rVa9nk0YUEaK0fVpfcUMsPyo5zBuk2JduEv5cSyeBJ1v8vwn2iyss5h2uTPVKAESV/EPvaCsLQ5xTL6ZnjOwp6VRdC4IsPyV4Hy9EcIr+gq0eI4kIQaI2uKN0ed4X2L9r9xTmFvgffZo6jnmR+P1fuZ4afPQuZZGRhlAjcZb6NJpXMAbTxjaWdtO+A6jukblW+08WfNch6qT2+QOHfDuHYtNiklUoSdxjWeZY29egg2qytiNdRyYHMnJQvEYr4jaikMb9mvitfj1PtoUnOy8cQqfhWyo0x3/QQBrVQV01t4K0C0szAGRZ6vQqA==
  template:
    metadata:
      creationTimestamp: null
      name: flood
      namespace: dn-downloads
    type: Opaque

