name: Flux Image Updates, Auto PR
on:
  create:
    branches: ['flux-image-updates']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "🤖 Flux CD image updates"
        pr_body: "*Automated PR beep boop* 🤖"
        pr_reviewer: "duckfullstop"
        github_token: ${{ secrets.GITHUB_TOKEN }}