apiVersion: v1
kind: Service
metadata:
  name: home-assistant-matter
  labels:
    app: home-assistant
spec:
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv6
  selector:
     app: home-assistant
  ports:
  - name: ws
    protocol: TCP
    port: 5580
    targetPort: 5580